<h2>Les différents data types  disponibles</h2>

Les éléments d’un tableaunumpyparticulier sont du même type, et on a vu les types suivants :int,floatetcomplex.En fait il y a d’autres types possibles et en voici la liste :


Les objets de type hiérarchique génériques sont convertis en objets de type correspondants selon les associations:


<a href=https://numpy.org/doc/stable/reference/arrays.dtypes.html>https://numpy.org/doc/stable/reference/arrays.dtypes.html</a>


<h2>Data Types in Python</h2>

Par défaut Python ont ces types de données:

    strings  - used to represent text data, the text is given under quote marks. eg. "ABCD"

    integer  - used to represent integer numbers. eg. -1, -2, -3

    float    - used to represent real numbers. eg. 1.2, 42.42

    boolean  - used to represent True or False.

    complex  - used to represent a number in complex plain. eg. 1.0 + 2.0j, 1.5 + 2.5j


<h2>DData Types in NumPy</h2>

NumPy a quelques types de données supplémentaires, et se réfère aux types de données avec un caractère, comme i pour les entiers, u pour les entiers non signés, etc. 
Voici une liste de tous les types de données dans NumPy et les caractères utilisés pour les représenter.

    i - integer
    b - boolean
    u - unsigned integer
    f - float
    c - complex float
    m - timedelta
    M - datetime
    O - object
    S - string
    U - unicode string
    V - fixed chunk of memory for other type ( void )

<a href=https://numpy.org/doc/stable/user/basics.types.html>https://numpy.org/doc/stable/user/basics.types.html</a>

<h2>Fonctions mathématiques avec NumPy</h2>

<b>Fonctions trigonométriques</b>

    numpy.sin(x)     -  sinus

    numpy.cos(x)     -  cosinus

    numpy.tan(x)     - tangente

    numpy.arcsin(x)  - arcsinus

    numpy.arccos(x)  - arccosinus

    numpy.arctan(x)  - arctangente


<b>Fonctions hyperboliques</b>

    numpy.sinh(x)    - sinus hyperbolique

    numpy.cosh(x)    - cosinus hyperbolique

    numpy.tanh(x)    - tangente hyperbolique

    numpy.arcsinh(x) - arcsinus hyperbolique

    numpy.arccosh(x) - arccosinus hyperbolique

    numpy.arctanh(x) - arctangente hyperbolique
    
<b>Fonctions diverses</b>

    numpy.sqrt(x)    - racine carrée

    numpy.exp(x)     - exponentielle

    numpy.log(x)     - logarithme népérien

    numpy.abs(x)     - valeur absolue

    numpy.sign(x)    - signe

<b>Fonctions utiles pour les nombres complexes</b>

    numpy.real(x)    - partie réelle

    numpy.imag(x)    - partie imaginaire

    numpy.abs(x)     - module

    numpy.angle(x)   - argument en radians

    numpy.conj(x)    - complexe conjugué
    

In [1]:
#np sera l’alias utilisé pour accéder aux  routines de la librairie numpy
import numpy as np

In [2]:
np.array(("123",'abcbde',"12XY5")) 


array(['123', 'abcbde', '12XY5'], dtype='<U6')

numpy.linspace() (resp. numpy.logspace()): répartition uniforme (resp. logarithmique) d’un nombre fixe de points entre un start et un end (préférable à numpy.arange() sur des réels).


In [3]:
v = np.linspace(0, 2*np.pi, 5, 5) # 5 nb entre 0 et 2π *inclus*, type réel par défaut
print(v)

[0.         1.57079633 3.14159265 4.71238898 6.28318531]


numpy.meshgrid() est similaire à numpy.linspace() en 2D ou plus:

In [4]:
# 5 points entre 0 et 2 en "x", et 3 entre 0 et 1 en "y"
x = np.linspace(0, 2, 5)
print(x)

[0.  0.5 1.  1.5 2. ]


In [5]:
y = np.linspace(0, 1, 3)
print(y)

[0.  0.5 1. ]


In [6]:
# Tableaux 2D des x et des y
xx, yy = np.meshgrid(x, y) 


In [7]:
#Tableau 2D des x, (3, 5)
print(xx)

[[0.  0.5 1.  1.5 2. ]
 [0.  0.5 1.  1.5 2. ]
 [0.  0.5 1.  1.5 2. ]]


In [8]:
#Tableau 2D des y, (3, 5)
print(yy)

[[0.  0.  0.  0.  0. ]
 [0.5 0.5 0.5 0.5 0.5]
 [1.  1.  1.  1.  1. ]]


numpy.mgrid permet de générer des rampes d’indices (entiers) ou de coordonnées (réels) de rang arbitraire avec une notation évoluée faisant appel aux Index tricks. Équivalent à numpy.linspace() en 1D et similaire (mais différent) à numpy.meshgrid() en 2D.

In [9]:
np.mgrid[0:4, 1:6:2]  # Grille 2D d'indices (entiers)

array([[[0, 0, 0],
        [1, 1, 1],
        [2, 2, 2],
        [3, 3, 3]],

       [[1, 3, 5],
        [1, 3, 5],
        [1, 3, 5],
        [1, 3, 5]]])

In [10]:
np.mgrid[0:2*np.pi:5j]  # Rampe de coordonnées (réels): 5 nb de 0 à 2π (inclus)

array([0.        , 1.57079633, 3.14159265, 4.71238898, 6.28318531])

In [11]:
# 3 points entre 0 et 1 selon l'axe 0, et 5 entre 0 et 2 selon l'axe 1
z = np.mgrid[0:1:3j, 0:2:5j]
print(z)

[[[0.  0.  0.  0.  0. ]
  [0.5 0.5 0.5 0.5 0.5]
  [1.  1.  1.  1.  1. ]]

 [[0.  0.5 1.  1.5 2. ]
  [0.  0.5 1.  1.5 2. ]
  [0.  0.5 1.  1.5 2. ]]]


In [12]:
z.shape

(2, 3, 5)

<b>Attention</b>
à l’ordre de variation des indices dans les tableaux multidimensionnels, et aux différences entre numpy.meshgrid() et numpy.mgrid.

numpy.random.rand() crée un tableau d’un format donné de réels aléatoires dans [0, 1[; numpy.random.randn() génère un tableau d’un format donné de réels tirés aléatoirement d’une distribution gaussienne (normale) standard N(μ=0,σ2=1).

In [13]:
<b>Attention</b>
à l’ordre de variation des indices dans les tableaux multidimensionnels, et aux différences entre numpy.meshgrid() et numpy.mgrid.



SyntaxError: invalid syntax (<ipython-input-13-84679d6c78bc>, line 1)

In [ ]:
y = np.linspace(0, 1, 3)
print(y)

In [ ]:
# Tableaux 2D des x et des y
xx, yy = np.meshgrid(x, y) 


In [ ]:
#Tableau 2D des x, (3, 5)
print(xx)

In [ ]:
#Tableau 2D des y, (3, 5)
print(yy)

numpy.mgrid permet de générer des rampes d’indices (entiers) ou de coordonnées (réels) de rang arbitraire avec une notation évoluée faisant appel aux Index tricks. Équivalent à numpy.linspace() en 1D et similaire (mais différent) à numpy.meshgrid() en 2D.

In [ ]:
np.mgrid[0:4, 1:6:2]  # Grille 2D d'indices (entiers)

In [ ]:
np.mgrid[0:2*np.pi:5j]  # Rampe de coordonnées (réels): 5 nb de 0 à 2π (inclus)

In [ ]:
# 3 points entre 0 et 1 selon l'axe 0, et 5 entre 0 et 2 selon l'axe 1
z = np.mgrid[0:1:3j, 0:2:5j]
print(z)

In [ ]:
z.shape

<b>Attention</b>
à l’ordre de variation des indices dans les tableaux multidimensionnels, et aux différences entre numpy.meshgrid() et numpy.mgrid.

numpy.random.rand() crée un tableau d’un format donné de réels aléatoires dans [0, 1[ 

numpy.random.randn() génère un tableau d’un format donné de réels tirés aléatoirement d’une distribution gaussienne (normale) standard N(μ=0,σ2=1).


numpy fournit de nombreuses fonctions mathématiques de base (numpy.exp(), numpy.atan2(), etc.) s’appliquant directement sur les éléments des tableaux d’entrée:

Par définition, tous les éléments d’un tableau homogène doivent être du même type. Cependant, outre les types scalaires élémentaires – bool, int, float, complex, str, etc. – numpy supporte les types composés, c.-à-d. incluant plusieurs sous-éléments de types différents:

<h1>Tableaux évolués</h1>

In [ ]:
dt = np.dtype([('nom', 'U10'),    # 1er  élément: une chaîne de 10 caractères unicode
              ('age', 'i'),      # 2e élément: un entier
              ('taille', 'd')])  # 3e élément: un réel (double)

In [ ]:
arr = np.array([('Calvin', 6, 1.20), ('Hobbes', 5, 1.80)], dtype=dt)

print(arr)
print(arr.dtype)

In [ ]:
arr[0]

In [ ]:
arr['nom']

In [ ]:
rec = arr.view(np.recarray) #qui permet l’accès au champ en utilisant les attributs.
print(rec)

In [ ]:
rec.nom 

Les tableaux structurés sont très puissants pour manipuler des données (semi-)hétérogènes, p.ex. les entrées du catalogue CSV des objets de Messier Messier.csv:

Les objets de Messier sont une liste d'objets astronomiques catalogués par l'astronome français

In [ ]:
dt = np.dtype([('M', 'U3'),        # N° catalogue Messier
              ('NGC', 'i'),       # N° New General Catalogue
              ('Type', 'U2'),     # Code type
              ('Mag', 'f'),       # Magnitude
              ('Size', 'f'),      # Taille [arcmin]
              ('Distance', 'f'),  # Distance [pc]
              ('RA', 'f'),        # Ascension droite [h]
              ('Dec', 'f'),       # Déclinaison [deg]
              ('Con', 'U3'),      # Code constellation
              ('Season', 'U6'),   # Saison
              ('Name', 'U30')])   # Nom alternatif

In [ ]:
#genfromtxt Charger les données d’un fichier texte, avec les valeurs manquantes traitées comme spécifié.
messier = np.genfromtxt("Messier.csv", dtype=dt, delimiter=',', comments='#')

In [ ]:
messier[1]

<h2>Tableaux masqués</h2>

Le sous-module numpy.ma ajoute le support des tableaux masqués (Masked Arrays). Imaginons un tableau (4, 5) de réels (positifs ou négatifs), sur lequel nous voulons calculer pour chaque colonne la moyenne des éléments positifs uniquement:

In [ ]:
x = np.random.randn(4, 5)
print(x)

In [ ]:
x[x >= 0]  # Donne les éléments >0 du tableau, sans leur indice

In [ ]:
(x >= 0).nonzero() # Donne les indices ([i], [j]) des éléments positifs

In [ ]:
# ma.masked_less Masque un tableau dont la valeur est inférieure à une valeur donnée.
y = np.ma.masked_less(x, 0); # Tableau où les éléments < 0 sont masqués
print(y)

In [ ]:
m0 = y.mean(axis=0) # Moyenne sur les lignes (axe 0)
print(m0)

In [ ]:
m0.filled(-1) # Conversion en tableau normal

<h4>Note</h4>
Les tableaux évolués de numpy sont parfois suffisants, mais pour une utilisation avancée, il peut être plus pertinent d’invoquer les bibliothèques dédiées Pandas et xarray.

numpy fournit en outre quelques fonctionnalités supplémentaires, parmis lesquelles les sous-modules suivants:

    numpy.fft: Discrete Fourier Transform;

    numpy.random: valeurs aléatoires;

    numpy.polynomial: manipulation des polynômes (racines, polynômes orthogonaux, etc.).

Les tableaux structurés sont très puissants pour manipuler des données (semi-)hétérogènes, p.ex. les entrées du catalogue CSV des objets de Messier Messier.csv:

Les objets de Messier sont une liste d'objets astronomiques catalogués par l'astronome français

In [ ]:
dt = np.dtype([('M', 'U3'),        # N° catalogue Messier
              ('NGC', 'i'),       # N° New General Catalogue
              ('Type', 'U2'),     # Code type
              ('Mag', 'f'),       # Magnitude
              ('Size', 'f'),      # Taille [arcmin]
              ('Distance', 'f'),  # Distance [pc]
              ('RA', 'f'),        # Ascension droite [h]
              ('Dec', 'f'),       # Déclinaison [deg]
              ('Con', 'U3'),      # Code constellation
              ('Season', 'U6'),   # Saison
              ('Name', 'U30')])   # Nom alternatif

In [ ]:
#genfromtxt Charger les données d’un fichier texte, avec les valeurs manquantes traitées comme spécifié.
messier = np.genfromtxt("Messier.csv", dtype=dt, delimiter=',', comments='#')

In [ ]:
messier[1]

<h2>Tableaux masqués</h2>

Le sous-module numpy.ma ajoute le support des tableaux masqués (Masked Arrays). Imaginons un tableau (4, 5) de réels (positifs ou négatifs), sur lequel nous voulons calculer pour chaque colonne la moyenne des éléments positifs uniquement:

In [ ]:
x = np.random.randn(4, 5)
print(x)

In [ ]:
x[x >= 0]  # Donne les éléments >0 du tableau, sans leur indice

In [ ]:
(x >= 0).nonzero() # Donne les indices ([i], [j]) des éléments positifs

In [ ]:
# ma.masked_less Masque un tableau dont la valeur est inférieure à une valeur donnée.
y = np.ma.masked_less(x, 0); # Tableau où les éléments < 0 sont masqués
print(y)

In [ ]:
m0 = y.mean(axis=0) # Moyenne sur les lignes (axe 0)
print(m0)

In [ ]:
m0.filled(-1) # Conversion en tableau normal

<h4>Note</h4>
Les tableaux évolués de numpy sont parfois suffisants, mais pour une utilisation avancée, il peut être plus pertinent d’invoquer les bibliothèques dédiées Pandas et xarray.

numpy fournit en outre quelques fonctionnalités supplémentaires, parmis lesquelles les sous-modules suivants:

    numpy.fft: Discrete Fourier Transform;

    numpy.random: valeurs aléatoires;

    numpy.polynomial: manipulation des polynômes (racines, polynômes orthogonaux, etc.).