In [139]:
import numpy as np

# Indexation 
arr1d = np.array([1,2,3,4,5,6,7,8,9])
# Slicer les elements d'index 4 et 5
arr1d[4:6]

array([5, 6])

In [140]:
# Remplacer le chiffre 6 dans arr1d par le chiffre 126
arr1d[5] = 126
arr1d

array([  1,   2,   3,   4,   5, 126,   7,   8,   9])

In [141]:
# Remplacer tous les elements de arr_slice par 64
arr1d[4:6] = 64
arr1d

array([ 1,  2,  3,  4, 64, 64,  7,  8,  9])

In [142]:
arr2d = np.array([ [1,2,3],[4,5,6],[7,8,9] ])
arr2d
# Calculer la taille de arr2d
arr2d.shape

(3, 3)

In [143]:
# Afficher la troisieme matrice de arr2d
arr2d[2]

array([7, 8, 9])

In [144]:
# Acceder de deux maniere au chiffre 3 de la premiere sous matrice
arr2d = np.array([ [1,2,3],[4,5,6],[7,8,9] ])
arr2d[0][2]

3

In [145]:
arr2d = np.array([ [1,2,3],[4,5,6],[7,8,9] ])
arr2d[0][2:]

array([3])

In [146]:
# Axis 0 rows Axis 1 columns

In [147]:
# En multidimensionnel
arr3d = np.array([ [[1,2,3],[4,5,6]],[[7,8,9],[10,11,12]]])

In [148]:
arr3d.size

12

In [149]:
arr3d.ndim

3

In [150]:
arr3d.shape

(2, 2, 3)

In [151]:
# Acceder a la premiere matrice (si on oublie de preciser le deuxième indice on reduit de dimension)
arr3d[0]

array([[1, 2, 3],
       [4, 5, 6]])

In [152]:
# Acceder a la premiere matrice (autrement)
arr3d[:1]

array([[[1, 2, 3],
        [4, 5, 6]]])

In [153]:
# Acceder à la deuxieme smatrice
arr3d[1]

array([[ 7,  8,  9],
       [10, 11, 12]])

In [154]:
# Acceder à la deuxieme matrice (autrement)
arr3d[1:2]

array([[[ 7,  8,  9],
        [10, 11, 12]]])

In [155]:
# Acceder à la deuxieme sous-matrice de la deuxième matrice
arr3d[1][1]

array([10, 11, 12])

In [156]:
# Creation d'un array
v = np.array([1, 3, 2, 4])
print(v)

[1 3 2 4]


In [157]:
M = np.array([[1, 3], [2, 4]])
print(M)
print(M.shape)

[[1 3]
 [2 4]]
(2, 2)


In [158]:
print(M)

[[1 3]
 [2 4]]


In [159]:
# Type de M
# ndarray travaille avec 1 seul de type de données à la fois: optimise stockage memoire et temps de calcul
M.dtype


dtype('int64')

In [160]:
# nombre d'octets par element
M = np.array([1,2,4],dtype=np.int16)
print(M)
M.dtype

[1 2 4]


dtype('int16')

In [161]:
# nombre d'octets
M.size

3

In [162]:
M.itemsize / M.nbytes

0.3333333333333333

In [163]:
print(M)

[1 2 4]


In [164]:
# Assigner la valeur -1 au premier element de M
M[0]=-1

In [165]:
print(M)

[-1  2  4]


In [166]:
# Affecter une chaîne de caractere au premier element de M
M = np.array(["ali",1,2,4])
M= M.astype('S')
print(M)

[b'ali' b'1' b'2' b'4']


In [167]:
M.shape
M.dtype

dtype('S21')

In [173]:
a = np.array([0, 0, 0])
print(a.dtype)
# Assigner un float au premier element de 0
a= np.array([1,2,4],dtype=float)
print(a)
print(a.dtype)

int64
[1. 2. 4.]
float64


In [174]:
a = np.array([0, 0, 0])
print(a.dtype)
# Assigner un float au premier element de 0
a= np.array([1,2,4])
a= a.astype('f')
print(a)
print(a.dtype)

int64
[1. 2. 4.]
float32


In [176]:
# Declarer des float à partir d'un np.array dans la fonction array()

# Assigner un float au premier element de 0
a[0] = 3.2
a= a.astype('f')
print(a)

[3.2 2.  4. ]
