<h1>Numpy Manipulation des vecteur avec numpy<h1>

<p>Numpy est un package pour Python spécialisé dans la manipulation des  tableaux (array), pour nous essentiellement les vecteurs et les matrices</p>

<p>Les tableaux " numpy " ne gère que les objets de même type</p>

<p>Le package propose un grand nombre de routines pour un accès rapide  aux données (ex. recherche, extraction), pour les manipulations diverses
(ex. tri), pour les calculs (ex. calcul statistique)</p>

<p>Les tableaux " numpy " sont plus performants (rapidité, gestion de la  volumétrie) que les collections usuelles de Python</p>

<p>Les tableaux " numpy " sont sous-jacents à de nombreux packages dédiés au calcul scientifique sous Python.</p>

<h4>Attention, un vecteur est en réalité une matrice à 1 seule dimension</h4>

In [144]:
#np sera l’alias utilisé pour accéder aux  routines de la librairie numpy
import numpy as np

In [145]:
a =np.array([1.2,2.5,3.2,1.8])

#type de la structure

In [146]:
print(type(a)) #<class‘numpy.ndarray’>

<class 'numpy.ndarray'>


In [147]:
#type des données
print(a.dtype)  #float64

float64


In [148]:
#1 (on aura 2 si matrice,etc.)
print(a.ndim)

1


In [149]:
#nombre de lignes etcol
print(a.shape) #(4,) on a tuple ! 4 cases sur la 1ère dim(n°0)

(4,)


In [150]:
#nombre totale devaleurs
print(a.size)  #4, nb.lignes x nb.colonnes simatrice


4


Le typage des valeurs peut être implicite ou explicite

In [151]:
#création et typage implicite
a = np.array([1,2,4])
print(a.dtype) #int32


int64


In [152]:
#création et typage explicite –préférable !
a = np.array([1,2,4],dtype=float)
print(a.dtype) #float64
print(a) #[1. 2.4.]

float64
[1. 2. 4.]


In [153]:
#un vecteur de booléens est tout à fait possible
b=  np.array([True,False,True,True],dtype=bool)
print(b) #[TrueFalseTrueTrue]


[ True False  True  True]


Création d’un array d’objets  complexes (autres que les  types de base) estpossible


In [154]:
# la donnée peut être un objet python
a =np.array([{"Toto":(45,2000)},{"Tata":(34,1500)}])
print(a.dtype) #object


object


In [217]:
#suite arithmétique de raison 1
a =np.arange(start=0,stop=10)
print(a) #[0 1 2 3 4 5 6 7 8 9], attention dernière valeur est exclue

[0 1 2 3 4 5 6 7 8 9]


In [215]:
a = np.arange(10)
print(a)

[0 1 2 3 4 5 6 7 8 9]


In [156]:
#vecteur de valeurs identiques 1 – 1 seule dim et 5 valeurs
a = np.ones(shape=5)
print(a) # [1. 1. 1. 1. 1.]


[1. 1. 1. 1. 1.]


In [214]:
a = np.ones(shape=(3,4,5)) # 3 * ( 4 ligne  5 colone )
print(a) #

[[[1. 1. 1. 1. 1.]
  [1. 1. 1. 1. 1.]
  [1. 1. 1. 1. 1.]
  [1. 1. 1. 1. 1.]]

 [[1. 1. 1. 1. 1.]
  [1. 1. 1. 1. 1.]
  [1. 1. 1. 1. 1.]
  [1. 1. 1. 1. 1.]]

 [[1. 1. 1. 1. 1.]
  [1. 1. 1. 1. 1.]
  [1. 1. 1. 1. 1.]
  [1. 1. 1. 1. 1.]]]


In [219]:
# Pour changer les dimensions il existe la fonction numpy (reshape)

d = np.arange(60)
print(d)
# d.reshape(3,4,5) 

[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23
 24 25 26 27 28 29 30 31 32 33 34 35 36 37 38 39 40 41 42 43 44 45 46 47
 48 49 50 51 52 53 54 55 56 57 58 59]


In [157]:
#plus généralement – répétition 5 fois (1 dimension) de la valeur 3.2

a = np.full(shape=5,fill_value=3.2)
print(a) #[3.2 3.2 3.2 3.2 3.2]


[3.2 3.2 3.2 3.2 3.2]


Les données peuvent  être stockées dans un  fichier texte (loadtxt  pour charger, savetxt  poursauver)


In [158]:
#charger à partir d'un fichier
#typage explicitepossible

a = np.loadtxt("vecteur.txt",dtype=float)
print(a) #[4. 5. 8. 16. 68. 14. 35.]


[ 4.  5.  8. 16. 68. 14. 35.]


Conversion d’une  collection (type standard  Python) en type array de numpy

In [159]:
#liste de valeurs

lst = [1.2,3.1,4.5]
print(type(lst))  #<class‘list’>

#conversion à partir d'une liste

a = np.asarray(lst,dtype=float)

print(type(a)) #<class ‘numpy.ndarray’>
print(a) #[1.2 3.14.5]


<class 'list'>
<class 'numpy.ndarray'>
[1.2 3.1 4.5]


Rajouter une valeurendernière position

In [160]:
#vecteur de valeurs

a =np.array([1.2,2.5,3.2,1.8])

#ajouter une valeur ,  placée en dernière position

a =np.append(a,10)
print(a) #[1.2 2.5 3.2 1.810.]


[ 1.2  2.5  3.2  1.8 10. ]


Suppression d’une valeur via son indice

In [161]:
#suppression via indice

b = np.delete(a,2) #une plage d’indices est aussi possible
# print(b) #[1.2 2.5 1.810.]


Redimensionnement  explicite


In [162]:
a =np.array([1,2,3])

#redimensionnement

a.resize(5)
print(a) #[1 2 3 0 0], les nouvelles cases mises à0

[1 2 3 0 0]


In [163]:
#Concaténation de 2  vecteurs

x =np.array([1,2,5,6])
y =np.array([2,1,7,4])
z =np.append(x,y)
print(z) #[1 2 5 6 2 1 7 4]



[1 2 5 6 2 1 7 4]


<h1>Accéder aux valeurs via des indices ou desconditions</h1>
<h1>EXTRACTION DESVALEURS</h1>

In [164]:
v =np.array([1.2,7.4,4.2,8.5,6.3])

In [165]:
#toutes lesvaleurs

print(v)
# ou
print(v[:]) # noter le rôle du : , il faut lire ici début à fin


[1.2 7.4 4.2 8.5 6.3]
[1.2 7.4 4.2 8.5 6.3]


In [166]:
#accès indicé - premièrevaleur

print(v[0]) # 1.2 – Noter que le 1er indice est 0 (zéro)


1.2


In [167]:
#dernière valeur

print(v[v.size-1]) #6.3, v.size est ok parce que v   est unvecteur


6.3


In [168]:
#plage d'indicescontigus

print(v[1:3]) # [7.44.2]


[7.4 4.2]


In [169]:
#extrêmes, début à 3 (non-inclus)

print(v[:3]) # [1.2 7.44.2]

[1.2 7.4 4.2]


In [170]:
#extrêmes, 2 à fin

print(v[2:]) # [4.2 8.56.3]

[4.2 8.5 6.3]


In [171]:
#indice négatif

print(v[-1]) # 6.3, dernierélément

6.3


In [172]:
#indices négatifs

print(v[-3:]) # [4.2 8.5 6.3], 3 dernierséléments



[4.2 8.5 6.3]


<h2>Accès indicé –Ecriture générique</h2>



In [173]:
v =np.array([1.2,7.4,4.2,8.5,6.3])


La notation générique des indices est :  <b>début:fin:pas</b>  fin est non inclus dans laliste


In [174]:
#valeur n°1 à n°3 avec un pas de 1

print(v[1:4:1]) # [7.4, 4.2, 8.5]

[7.4 4.2 8.5]


In [175]:
#le pas de 1 est implicite

print(v[1:4]) # [7.4, 4.2,8.5]


[7.4 4.2 8.5]


In [176]:
#n°0 à n°2 avec un pas de 2

print(v[0:3:2]) # [1.2,4.2]


[1.2 4.2]


In [177]:
#le pas peut être négatif, n°3 à n°1 avec un pas de -1

print (v[3:0:-1])  # [8.5, 4.2,7.4]


[8.5 4.2 7.4]


In [178]:
#on peut exploiter cette idée pour inverser un vecteur

print(v[::-1]) # [6.3, 8.5, 4.2, 7.4, 1.2]


[6.3 8.5 4.2 7.4 1.2]


<h2>Accès par conditions –Indiçage booléen</h2>

In [179]:
#extraction avec un vecteur debooléens

v =np.array([1.2,7.4,4.2,8.5,6.3])
b = np.array([False,True,False,True,False],dtype=bool)
print(v[b]) # [7.4 8.5]

[7.4 8.5]


In [180]:
#on peut utiliser une condition pour l'extraction

print(v[v < 2]) # [1.2 4.26.3]


[1.2]


In [181]:
#parce que la condition est un vecteur de booléen

b = v < 2
print(b) # [True False True FalseTrue]
print(type(b)) # <class‘numpy.ndarray’>


[ True False False False False]
<class 'numpy.ndarray'>


In [182]:
#on peut utiliser la fonction extract()
#v =np.array([1.2,7.4,4.2,8.5,6.3])

c = np.array(["er","et","ki","sdf","ee"])
print(np.extract(v < 5, c)) # [1.2 4.26.3]


['er' 'ki']


<h2>Tri et recherche</h2>

In [183]:
v =np.array([1.2,7.4,4.2,8.5,6.3])


In [184]:
#recherche valeur max

print(np.max(v)) # 8.5
print(v.max())


8.5
8.5


In [185]:
#recherche indice de valeur max

print(np.argmax(v)) # 3
print(v.argmax()) # 3



3
3


In [186]:
#tri des valeurs

print(np.sort(v)) # [1.2 4.26.37.4 8.5]


[1.2 4.2 6.3 7.4 8.5]


In [187]:
#récupération des indices triés

print(np.argsort(v)) # [0  2  4 1 3]
print(v.argsort()) # [0  2  4 1 3]

[0 2 4 1 3]
[0 2 4 1 3]


In [188]:
#valeurs distinctes

a =np.array([1,2,2,1,1,2,3,3,5])
print(np.unique(a)) # [1 2 3 5]




[1 2 3 5]


<h1> CALCULS SUR LES VECTEURS </h1>
<h2>Calculs (statistiques) récapitulatifs</h2>


In [189]:
#moyenne

print(np.mean(v)) # 5.52
print(v.mean()) # 5.52


5.5200000000000005
5.5200000000000005


In [190]:
#médiane

print(np.median(v)) # 6.3


6.3


la variance est une mesure de la dispersion des valeurs d'un échantillon ou d'une distribution de probabilité. Elle exprime la moyenne des carrés des écarts à la moyenne, aussi égale à la différence entre la moyenne des carrés des valeurs de la variable et le carré de la moyenne, selon le théorème de König-Huygens.

#variance
print(np.var(v)) # 6.6856
print(v.var()) # 6.6856


In [191]:
#quantile

print(np.percentile(v,50)) #6.3 (50% =médiane)


6.3


In [192]:
#somme

print(np.sum(v)) # 27.6
print(v.sum()) # 27.6


27.6
27.6


In [193]:
#somme cumulée

print(np.cumsum(v)) # [1.2 8.6 12.8 21.327.6]
print(v.cumsum()) # [1.2 8.6 12.8 21.327.6]


[ 1.2  8.6 12.8 21.3 27.6]
[ 1.2  8.6 12.8 21.3 27.6]


<h2>Calculs entre vecteurs</h2>
Principe :Les calculs se font élément par élément (elemenstwise) entre vecteurs « numpy » -
On a le  même principe sous R.

In [194]:
#calculs entre vecteurs

x = np.array([1.2,1.3,1.0])
y = np.array([2.1,0.8,1.3])

In [195]:
#multiplication

print(x*y) # [2.52 1.04 1.3]


[2.52 1.04 1.3 ]


In [196]:
#addition

print(x+y) # [3.3 2.1 2.3]


[3.3 2.1 2.3]


In [197]:
#multiplication par un scalaire

print(2*x) # [2.4 2.6 2. ]

[2.4 2.6 2. ]


In [198]:
#comparaison de vecteurs

x = np.array([1,2,5,6])
y = np.array([2,1,7,4])
b = x > y
print(b) # [False True False True]

[False  True False  True]


In [199]:
#opérations logiques

a = np.array([True,True,False,True],dtype=bool)
b = np.array([True,False,True,False],dtype=bool)


In [200]:
#ET logique

print(np.logical_and(a,b)) # [True False FalseFalse]

#OU exclusif logiquen

print(np.logical_xor(a,b)) # [False True TrueTrue]


[ True False False False]
[False  True  True  True]


<h2> Fonctions matricielles </2>


In [201]:
x = np.array([1.2,1.3,1.0])
y = np.array([2.1,0.8,1.3])

In [202]:
#produit scalaire

z = np.vdot(x,y)
print(z) # 4.86

4.86


In [203]:
#ou l’équivalent calculé

print(np.sum(x*y)) # 4.86
print((x*y).sum()) # 4.86


4.86
4.86


In [204]:
#norme d'un vecteur

n = np.linalg.norm(x)
print(n)# 2.03


2.0322401432901573


In [205]:
#ou l’équivalent calculé sqrt racine carrée

import math
print(math.sqrt(np.sum(x**2))) # 2.03

2.0322401432901573


<h2>Opérations ensemblistes</h2>
Principe: Un vecteur de valeurs (sur tout entières) peut être considéré comme un ensemble de valeurs.

In [206]:
#opérations ensemblistes

x = np.array([1,2,5,6])
y = np.array([2,1,7,4])

In [207]:
#intersection

print(np.intersect1d(x,y)) # [1 2]

[1 2]


In [208]:
#union – attention, ce n’est pas une concaténation

print(np.union1d(x,y)) # [1 2 4 5 6 7]

[1 2 4 5 6 7]


In [209]:
#différence c.à-d. qui sont dans x et pas dans y

print(np.setdiff1d(x,y)) # [56]

[5 6]
