<h1>Manipulation des matrices avec numpy<h1>

• Numpy est un package pour Python spécialisé dans la manipulation des  tableaux (array), pour nous essentiellement les vecteurs et lesmatrices

• Les tableaux « numpy » ne gère que les objets de même type•Le package propose un grand nombre de routines pour un accès rapide  aux données (ex. recherche, extraction), pour les manipulationsdiverses(ex. tri), pour les calculs (ex. calculstatistique)

• Les tableaux « numpy » sont plus performants (rapidité, gestion de la  volumétrie) que les collections usuelles de Python

• Les tableaux « numpy » sont sous-jacents à de nombreuxpackagesdédiés au calcul scientifique sousPython.

• Une matrice est un tableau (array) à 2dimensions

<h4>Il   n’est pas possible de tout aborder dans ce support. Pour aller plus loin,voirabsolument le manuel de référence (utilisé pour préparer cediaporama).</h4>

<h4><a href="http://docs.scipy.org/doc/numpy/reference/index.html">http://docs.scipy.org/doc/numpy/reference/index.html</a></h4>

Création à la volée, génération d’une séquence, chargement à partir d’unfichier
CRÉATION D’UNE MATRICE

In [3]:
import numpy as np

In [4]:
#Noter le rôle des [ ] et  [ ] pour délimiter les  portions de la matrice
a = np.array([ [1.2,2.5],[3.2,1.8],[1.1,4.3] ])


In [5]:
#type de lastructure
print(type(a)) #<class‘numpy.ndarray’>


<class 'numpy.ndarray'>


In [6]:
#type desdonnées
print(a.dtype) # float64


float64


In [7]:
#nombre dedimensions
print(a.ndim) #2 (car c ’est  une matrice)

2


In [8]:
#nombre de lignes et col, shape renvoie un tuple
# a = np.array([ 
#               [1.2,2.5],
#               [3.2,1.8],
#               [1.1,4.3] ])
print(a.shape) #(3,2) 3 lignes et 2 colonnes


(3, 2)


In [54]:
#nombre totale de valeurs
print(a.size)  #6, nb.lignes x nb.colonnes


6


<h2>Typage desdonnées</2>


In [10]:
#print del’ensemble
print(a)

[[1.2 2.5]
 [3.2 1.8]
 [1.1 4.3]]


In [11]:
#création et typage implicite
a = np.array([[1,2],[4,7]])
print(a.dtype) #int32


int64


In [55]:
#création et typage explicite –préférable !
a = np.array([[1,2],[4,7]],dtype=float)
print(a)
print(a.dtype) #float64

[[1. 2.]
 [4. 7.]]
float64


Tout comme pour les vecteurs, la création d’unematriced’objets complexes (autres que les types de base) estpossible

<h2>Créationd’une matrice à  partir d’une séquence de valeurs</h2>

arange() génère une séquence de valeurs, 0 à 9.
reshape() se charge de les réorganiser en matrice  2 lignes et 5 colonnes

In [13]:
#création à partir d'une séquence
# #attention les dim. doivent être compatibles
a = np.arange(0,10).reshape(2,5)
print(a)

[[0 1 2 3 4]
 [5 6 7 8 9]]


In [64]:
#un vecteur peut être converti en matrice
a =np.array([2.1,3.4,6.7,8.1,3.5,7.2])
print(a.shape) # (6,)


(6,)


In [65]:
#redim. en 3 lignes x 2 col.
b = a.reshape(2,3)
print(b.shape) # (2, 3)
print(b)


(2, 3)
[[2.1 3.4 6.7]
 [8.1 3.5 7.2]]


In [68]:
#matrices de valeurs identiques
#ex. pour une initialisation
a = np.zeros(shape=(2,4))
print(a)

[[0. 0. 0. 0.]
 [0. 0. 0. 0.]]


In [17]:
#plus généralement
a = np.full(shape=(2,4),fill_value=0.1)
print(a)



[[0.1 0.1 0.1 0.1]
 [0.1 0.1 0.1 0.1]]


<h2>Chargement à partir d’un fichier - Conversions<h2>


In [75]:
#charger à partir d'un fichier, typage explicite
a =np.loadtxt("mat.txt",delimiter=",",dtype=float)
print(a)

[[ 45.  62. 168.]
 [ 34.  68. 187.]
 [ 53.  85. 159.]]


In [19]:
#liste devaleurs
lst = [1.2,3.1,4.5,6.3]
print(type(lst)) # <class‘list’>


<class 'list'>


In [77]:
#conversion à partir d'une liste : 2 étapes asarray() etreshape()
a =np.asarray(lst,dtype=float).reshape(2,2)
print(a)


[[1.2 3.1]
 [4.5 6.3]]


<h2>Redimensionnement<h2>

In [21]:
#matrice de valeurs
a = np.array([[1.2,2.5],[3.2,1.8],[1.1,4.3]])

In [22]:
#ajouter une ligne – marche pour la concaténation de matrices
#Accoler le vecteur b en tant que  nouvelle ligne (axis = 0) de la  matricea
b = np.array([[4.1,2.6]])
c =np.append(a,b,axis=0)
print(c)

[[1.2 2.5]
 [3.2 1.8]
 [1.1 4.3]
 [4.1 2.6]]


In [23]:
#ajouter une colonne
#Accoler le vecteur den tantque nouvelle colonne(axis= 1) de la matrice
d =np.array([[7.8],[6.1],[5.4]])
print(np.append(a,d,axis=1))


[[1.2 2.5 7.8]
 [3.2 1.8 6.1]
 [1.1 4.3 5.4]]


In [24]:
#insertion
#Insertion de b en tant que nouvelle  ligne (axis = 0) à la positionn°1

print(np.insert(a,1,b,axis=0))


[[1.2 2.5]
 [4.1 2.6]
 [3.2 1.8]
 [1.1 4.3]]


In [25]:
#suppression
#Suppression de la ligne (axis = 0)  via son indice(n°1)
#a = np.array([[1.2,2.5],[3.2,1.8],[1.1,4.3]])
print(np.delete(a,1,axis=0))


[[1.2 2.5]
 [1.1 4.3]]


In [26]:
#modifier la dimension d'une matrice existante
#parcourt les données lignes par ligne
#Redimensionnement  d’une matrice
h = np.resize(a,new_shape=(2,3))
print(h)

[[1.2 2.5 3.2]
 [1.8 1.1 4.3]]


<h1>EXTRACTION DES VALEURS</h1>
<h3>Accéder aux valeurs via des indices ou desconditions<h3>


<h2>Accès indicé – Plages d’indices</h2>



In [27]:
v = np.array([[1.2,2.5],[3.2,1.8],[1.1,4.3]])

In [28]:
#affichage de la structure dans son ensemble
print(v)


[[1.2 2.5]
 [3.2 1.8]
 [1.1 4.3]]


In [81]:
#accès indicé - premièrevaleur
print(v[0,0]) # 1.2


1.2


In [30]:
#dernière valeur – noter l’utilisation de shape (qui est un tuple)
print(v[v.shape[0]-1,v.shape[1]-1]) # 4.3


4.3


In [31]:
#autre solution pour affichage de toutes les valeurs, noter le rôle des :
print(v[:,:])


[[1.2 2.5]
 [3.2 1.8]
 [1.1 4.3]]


In [86]:
#plage d'indices contigus : lignes 0 à 1 (2 non inclus), toutes les colonnes
print(v[0:2,:])


[[1.2 2.5]
 [3.2 1.8]]


In [33]:
#extrêmes, début to 2 (non-inclus)
print(v[:2,:])

[[1.2 2.5]
 [3.2 1.8]]


In [34]:
#extrêmes, lignes 1 à dernière
print(v[1:,:])


[[3.2 1.8]
 [1.1 4.3]]


In [35]:
#indice négatif – dernière ligne et toutes les colonnes
print(v[-1,:])

[1.1 4.3]


In [36]:
#indices négatifs – deux dernières lignes et toutes les colonnes
print(v[-2:,:])

[[3.2 1.8]
 [1.1 4.3]]


<h2>Accès par conditions – Indiçage booléen</h2>

In [37]:
#indiçage par vecteur de booléens
#si b trop court, tout le reste est considéré False
b = np.array([True,False,True],dtype=bool)
print(v[b,:])


[[1.2 2.5]
 [1.1 4.3]]


#exemple illustratif : extraire la lignes dont la somme est la pluspetite


In [38]:
#calculer la somme des colonnes pour chaque ligne
s = np.sum(v,axis=1)
print(s) # [ 3.7 5. 5.4]

[3.7 5.  5.4]


In [39]:
#repérer les lignes dont la somme est égale au minimum
#il est possible qu’il y en ait plusieurs
b = (s == np.min(s))
print(b) # [ True False False]

[ True False False]


In [40]:
#application du filtre booléen
print(v[b,:])



[[1.2 2.5]]


<h2>Tri etrecherche</h2>



In [41]:
#recherche valeur max des lignes (axis = 0) pour chaque colonne
print(np.max( v,  axis=0)) # [ 3.24.3 ] -- décryptage : 3.2 est la max des lignes  pour la colonne 0, 4.3 est la max des lignes pour la colonne1


[3.2 4.3]


In [42]:
#recherche valeur max des colonnes (axis = 1) pour chaque ligne
print(np.max( v,  axis=1)) # [ 2.5 3.24.3]

[2.5 3.2 4.3]


In [43]:
#recherche indice de valeur max des lignes (axis = 0) pour chaque colonne
print(np.argmax( v,axis=0)) # [ 12 ]


[1 2]


In [44]:
#tri des lignes (axis = 0) pour chaque colonne
#la relation entre les valeurs d'une même ligne est perdue !!!
print(np.sort( v,axis=0))

[[1.1 1.8]
 [1.2 2.5]
 [3.2 4.3]]


In [45]:
#récupération des indices triés
print(np.argsort( v,axis=0))

[[2 1]
 [0 0]
 [1 2]]


<h1>ITÉRATIONS</h1>
<h4>Stratégies pour parcourir unematrice</h4>


Avec les indices, nous pouvons accéder aux valeurs de la matrice  comme bon nous semble (ligne par ligne ou colonne parcolonne)


In [46]:
v =np.array([[1.2,2.5],[3.2,1.8],[1.1,4.3]])


In [47]:
#boucles indicées
s =0.0
for i in range(0,v.shape[0]):
    for j in range(0,v.shape[1]):
        print(v[i,j])
        s = s +v[i,j]
    print("Somme = ",s)


1.2
2.5
Somme =  3.7
3.2
1.8
Somme =  8.700000000000001
1.1
4.3
Somme =  14.100000000000001


<h2> Parcoursd’unematrice: lesitérateurs</h2>



Avec les itérateurs, nous pouvons accéder aux valeurs de la  matrice sans avoir à   recourir aux indices (ligne par ligne,  colonne parcolonne)


In [48]:
#itérateur - accès ligne parligne
# s =0.0
for x in np.nditer(v):
    print(x)
    s = s + x
print("Somme = ",s)


1.2
2.5
3.2
1.8
1.1
4.3
Somme =  28.200000000000003


In [49]:
#itérateur - accès colonne par colonne
# #"F" pour " Fortran order"
s =0.0
for x in np.nditer( v,order="F"):
    print(x)
    s = s +x
print("Somme = ",s)


1.2
3.2
1.1
2.5
1.8
4.3
Somme =  14.100000000000001


<h1>CALCULS SUR LESMATRICES</h1>
<h4>Calculsstatistiques</h4>


Principe : les calculs  sont réalisés selon un  axe (0 : traitement des  valeurs en ligne pour  chaque colonne, 1 :  inversement)

In [50]:
#moyenne des lignes pour chaque colonne
print(np.mean( v,axis=0)) # [1.8332.867]

[1.83333333 2.86666667]


In [51]:
#moyenne des colonnes pour chaque ligne
print(np.mean( v,axis=1)) # [1.852.52.7]



[1.85 2.5  2.7 ]


In [52]:
#somme cumulée des valeurs en ligne pour chaque colonne
print(np.cumsum( v,axis=0))


[[1.2 2.5]
 [4.4 4.3]
 [5.5 8.6]]


In [53]:
#matrice decorrélation
#rowvar = 0 pour indiquer que les variables
#sont organisés en colonnes
m = np.corrcoef( v,rowvar=0)
print(m)

[[ 1.         -0.74507396]
 [-0.74507396  1.        ]]


<b>La librairie n’est pas très fournie, nous aurons besoin de SciPy (etautres)</b>

